/*
Orthohack
Copyright 2016 Russell Leidich
http://orthohack.blogspot.com

This collection of files constitutes the Orthohack Library. (This is a
library in the abstact sense; it's not intended to compile to a ".lib"
file.)

The Orthohack Library is free software: you can redistribute it and/or
modify it under the terms of the GNU Limited General Public License as
published by the Free Software Foundation, version 3.

The Orthohack Library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Limited General Public License version 3 for more details.

You should have received a copy of the GNU Limited General Public
License version 3 along with the Orthohack Library (filename
"COPYING"). If not, see http://www.gnu.org/licenses/ .
*/
/*
Change the settings in this file to optimize precision vs. performance. You can even add support for new numerical types (fixed point or high-precision floating point). Complex or quaternion types would require changing the code, however.

Change this path to whatever you need. This is where all the data is located. Path separtors: double backslashes divide paths in Windows; single slashes divide them in UNIX. MUST end in (a path separtor, "\\" or "/") followed by "\x00" (NULL).
*/
u8 *pathname_base="./demo/idct_8x8/\x00";
/*
Change this output file to whatever you like. ".ohk" is recommended, identifying the file as Orthohack output.
*/
u8 *filename_base="./demo/idct_8x8/idct_8x8.ohk\x00";
/*
COEFF_COUNT, >1, is the number of real coefficients generated by the transform. For example, an 8x8 real discrete cosine transform generates 0x40 coefficients. This is also the number of files with sequential 9-digit decimal filenames which will be processed, starting with 000000000.bin .
*/
#define COEFF_COUNT 0x40
/*
OVERFLOW_CHECK will cause various overflow checks to occur. This value will automatically be turned off in production, as this file is not included in production code. If you wish to turn it off entirely, comment out the line (don't set it to 0).
*/
#define OVERFLOW_CHECK 1
/*
PRECISION_RATIO_LIMIT informs Orthohack about the noise level of the incoming data. It's difficult to explain the exact significance, but smaller means greater accuracy, but more coefficients and a slower transform -- perhaps unnecessarily so, if in fact some of the coefficients are only trivially different. Experiment and see where things gel. Must be >=1.0 and, for practical purposes, much closer to 1 than 2. 1.0 provides maximum accuracy at the expense of the performance of both Orthohack and the transform that it generates.
*/
#define PRECISION_RATIO_LIMIT (1+(1.0E-9))
/*
PRECISION_ZERO_LIMIT is the magnitude less than or equal to which an orthobasis sample may be overwritten with 0.0. However, generated ratios may still fall outside the range of this number and its reciprocal. Must be >=0.0 and, for practical purposes, much closer to 0 than 1. 0.0 provides maximum accuracy at the expense of the performance of both Orthohack and the transform that it generates.
*/
#define PRECISION_ZERO_LIMIT (1.0E-11)
/*
SAMPLE_COUNT, >1, is the number of 8-byte (NUMBER_IN)s stored in each file, starting with 000000000.bin . This is the number of spatial samples which are input to the transform. Usually but not always equal to COEFF_COUNT.
*/
#define SAMPLE_COUNT 0x40
/*
SIMULTHREAD_IDX_MAX is purely an unsigned 32-bit optimization parameter. Experiment. Higher values use more memory and do not necessarily imply greater speed.
*/
#define SIMULTHREAD_IDX_MAX 0x55
