rm orthohack.h
rm literal
rm post
rm pre
rm verify
rm demo/dct_8x8_demo
rm demo/dct_8x8_orthohack.h
rm demo/dct_8x8_ortholiteral.c
rm demo/dct_8x8/dct_8x8.ohk
rm demo/idct_8x8_demo
rm demo/idct_8x8_orthohack.h
rm demo/idct_8x8_ortholiteral.c
rm demo/idct_8x8/idct_8x8.ohk
